
echo "CREATE USER evbUser IDENTIFIED BY evbUser;" | sqlplus -s SYSTEM/oracle 
echo "GRANT CONNECT, RESOURCE TO evbUser;" | sqlplus -s SYSTEM/oracle 
echo "create tablespace ts_utils_data datafile 'ts_utils_data.dbf' size 20M autoextend on next 20M maxsize 2048m;" | sqlplus -s SYSTEM/oracle 
echo "create tablespace ts_utils_idx datafile 'ts_utils_idx.dbf' size 20M autoextend on next 20M maxsize 2048m;" | sqlplus -s SYSTEM/oracle 
echo "alter user evbUser default tablespace ts_utils_data;" | sqlplus -s SYSTEM/oracle 
echo "alter user evbUser quota unlimited on ts_utils_data;" | sqlplus -s SYSTEM/oracle 
echo "alter user evbUser quota unlimited on ts_utils_idx;" | sqlplus -s SYSTEM/oracle 

echo "CREATE TABLE \"EVBUSER\".\"EVB_BANK_OBJECT_CMS\" (\"OBJ_ID\" NUMBER, \"OBJ_TYPE\" VARCHAR2(50 CHAR), \"OBJ_NAME\" VARCHAR2(255 CHAR), \"LOCALIZATION\" VARCHAR2(255 CHAR), \"PLACE\" VARCHAR2(255 CHAR), \"ADDRESS\" VARCHAR2(255 CHAR), \"ZIP_CODE\" VARCHAR2(10 BYTE), \"LATITUDE\" NUMBER(12,8), \"LONGITUDE\" NUMBER(12,8), \"POST_SERVICE\" CHAR(1 BYTE) DEFAULT 'N', \"BANK_SERVICE\" CHAR(1 BYTE) DEFAULT 'Y', \"CLOSED_VALUE\" VARCHAR2(255 CHAR), \"MON_FROM\" VARCHAR2(5 BYTE), \"MON_TO\" VARCHAR2(5 BYTE), \"TUE_FROM\" VARCHAR2(5 BYTE), \"TUE_TO\" VARCHAR2(5 BYTE), \"GEOHASH\" VARCHAR2(12 CHAR), \"GEOHASH3\" VARCHAR2(3 CHAR) GENERATED ALWAYS AS (SUBSTR(TRIM(\"GEOHASH\"),1,3)) VIRTUAL VISIBLE , \"COS_RAD_LONG\" NUMBER(12,10) GENERATED ALWAYS AS (COS(0.0174532925*\"LONGITUDE\")) VIRTUAL VISIBLE , \"COS_RAD_LAT\" NUMBER(12,10) GENERATED ALWAYS AS (COS(0.0174532925*\"LATITUDE\")) VIRTUAL VISIBLE , \"SIN_RAD_LAT\" NUMBER(12,10) GENERATED ALWAYS AS (SIN(0.0174532925*\"LATITUDE\")) VIRTUAL VISIBLE , \"WED_FROM\" VARCHAR2(5 BYTE), \"WED_TO\" VARCHAR2(5 BYTE), \"THU_FROM\" VARCHAR2(5 BYTE), \"THU_TO\" VARCHAR2(5 BYTE), \"FRI_FROM\" VARCHAR2(5 BYTE), \"FRI_TO\" VARCHAR2(5 BYTE), \"SAT_FROM\" VARCHAR2(5 BYTE), \"SAT_TO\" VARCHAR2(5 BYTE), \"SUN_FROM\" VARCHAR2(5 BYTE), \"SUN_TO\" VARCHAR2(5 BYTE), \"GBITS\" NUMBER(20,0)) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE \"TS_UTILS_DATA\" ;" | sqlplus -s SYSTEM/oracle 
echo "CREATE UNIQUE INDEX \"EVBUSER\".\"EVB_BANK_OBJECT_CMS_PK\" ON \"EVBUSER\".\"EVB_BANK_OBJECT_CMS\" (\"OBJ_ID\") PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE \"TS_UTILS_DATA\" ;" | sqlplus -s SYSTEM/oracle 
echo "CREATE INDEX \"EVBUSER\".\"EVB_BANK_CMS_GEOHSH_IDX\" ON \"EVBUSER\".\"EVB_BANK_OBJECT_CMS\" (\"GEOHASH\") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE \"TS_UTILS_DATA\" ;" | sqlplus -s SYSTEM/oracle 
echo "CREATE INDEX \"EVBUSER\".\"EVB_BANK_CMS_LAT_LON_IDX\" ON \"EVBUSER\".\"EVB_BANK_OBJECT_CMS\" (\"LATITUDE\", \"LONGITUDE\") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE \"TS_UTILS_DATA\" ;" | sqlplus -s SYSTEM/oracle 
echo "ALTER TABLE \"EVBUSER\".\"EVB_BANK_OBJECT_CMS\" ADD CONSTRAINT \"EVB_BANK_CMS_TYPE_CHK\" CHECK (OBJ_TYPE IN ('OUTPOST', 'ATM','CDM','BRANCH','OFFICE')) ENABLE;" | sqlplus -s SYSTEM/oracle 
echo "ALTER TABLE \"EVBUSER\".\"EVB_BANK_OBJECT_CMS\" ADD CONSTRAINT \"EVB_BANK_OBJECT_CMS_PK\" PRIMARY KEY (\"OBJ_ID\") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE \"TS_UTILS_DATA\"  ENABLE;" | sqlplus -s SYSTEM/oracle 
echo "ALTER TABLE \"EVBUSER\".\"EVB_BANK_OBJECT_CMS\" MODIFY (\"GEOHASH\" NOT NULL ENABLE);" | sqlplus -s SYSTEM/oracle 
echo "ALTER TABLE \"EVBUSER\".\"EVB_BANK_OBJECT_CMS\" MODIFY (\"BANK_SERVICE\" NOT NULL ENABLE);" | sqlplus -s SYSTEM/oracle 
echo "ALTER TABLE \"EVBUSER\".\"EVB_BANK_OBJECT_CMS\" MODIFY (\"POST_SERVICE\" NOT NULL ENABLE);" | sqlplus -s SYSTEM/oracle 
echo "ALTER TABLE \"EVBUSER\".\"EVB_BANK_OBJECT_CMS\" MODIFY (\"LONGITUDE\" NOT NULL ENABLE);" | sqlplus -s SYSTEM/oracle 
echo "ALTER TABLE \"EVBUSER\".\"EVB_BANK_OBJECT_CMS\" MODIFY (\"LATITUDE\" NOT NULL ENABLE);" | sqlplus -s SYSTEM/oracle 
echo "ALTER TABLE \"EVBUSER\".\"EVB_BANK_OBJECT_CMS\" MODIFY (\"OBJ_NAME\" NOT NULL ENABLE);" | sqlplus -s SYSTEM/oracle 
echo "ALTER TABLE \"EVBUSER\".\"EVB_BANK_OBJECT_CMS\" MODIFY (\"OBJ_TYPE\" NOT NULL ENABLE);" | sqlplus -s SYSTEM/oracle 
echo "ALTER TABLE \"EVBUSER\".\"EVB_BANK_OBJECT_CMS\" MODIFY (\"OBJ_ID\" NOT NULL ENABLE);" | sqlplus -s SYSTEM/oracle 

echo "GRANT SELECT ON sys.dba_pending_transactions TO evbUser;" | sqlplus -s SYS/oracle AS SYSDBA
echo "GRANT SELECT ON sys.pending_trans$ TO evbUser;" | sqlplus -s SYS/oracle AS SYSDBA
echo "GRANT SELECT ON sys.dba_2pc_pending TO evbUser;" | sqlplus -s SYS/oracle AS SYSDBA
echo "GRANT EXECUTE ON sys.dbms_xa TO evbUser;" | sqlplus -s SYS/oracle AS SYSDBA
echo "GRANT FORCE ANY TRANSACTION TO evbUser;" | sqlplus -s SYSTEM/oracle

imp evbUser/evbUser@XE file=/tmp/dbaexp.dmp log=./dba.log fromuser=evbUser touser=evbUser
